# False discovery rate p-value correction.

### SciPy
I am going to use https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.false_discovery_control.html
It states the parameters:
- ps: 1D array like (the p-vaues to adjust)
- axis: if none, ps is aveled before performing the adjustment
- method: there are two methods
	- 'bh' = Benjamini-Hochberg (for independent or positively dependent)
	- 'by' = Benjaminini-Yekutieli (Controls the FDR under any dependency structure, including arbitrary dependence among the tests).

 [] For now I will use 'by' considering I am not 100% sure of independence.

In [1]:
import os
import yaml
import argparse
import pandas as pd
from scipy import stats

In [2]:
ldsc_csv = pd.read_csv("/home/maria/git/SOROLLA/Results/ldsc_genetic_correlation.csv")

In [3]:
ldsc_csv

,id_1,label_1,id_2,label_2,rg,se,z,p,h2_obs,h2_obs_se,h2_int,h2_int_se,gcov_int,gcov_int_se
0,GCST90042682,depression-family-mother,GCST90011808,prostate-cancer-3,-0.0540,0.0842,-0.6406,5.218000e-01,0.0332,0.0046,1.0536,0.0197,0.0092,0.0054
1,GCST90011816,cervical-cancer-2,GCST90042670,prostate-cancer-father,-0.0502,0.1571,-0.3197,7.492000e-01,0.0066,0.0013,1.0194,0.0085,0.0002,0.0051
2,GCST004748,lung-carcinoma-1,GCST90042696,prostate-cancer-sibling,0.0305,0.1860,0.1640,8.697000e-01,0.0013,0.0011,1.0049,0.0063,-0.0020,0.0052
3,GCST003769,depression-symptoms,GCST90043894,prostate-cancer-1,-0.0065,0.0700,-0.0922,9.265000e-01,0.0255,0.0037,1.0467,0.0156,0.0050,0.0052
4,GCST90255675,crc-cancer-1,GCST90275154,mdd-sex-M1,0.0844,0.0382,2.2088,2.720000e-02,0.1190,0.0093,1.0270,0.0076,-0.0034,0.0060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011,GCST90041833,breast-neoplasm-2,GCST90011809,melanoma-1,0.0864,0.1095,0.7886,4.303000e-01,0.0088,0.0023,1.0018,0.0089,0.0096,0.0054
2012,GCST004744,adenocarcinoma-lung,GCST90042843,anxiety-treatment-1,0.0168,0.0828,0.2025,8.395000e-01,0.0381,0.0044,0.9963,0.0071,-0.0027,0.0050
2013,GCST90275148,ADHD-sex-M1,GCST90225529,anxiety-others,0.3233,0.0539,6.0040,1.924600e-09,0.0088,0.0010,1.0171,0.0075,0.0059,0.0060
2014,GCST90043889,breast-neoplasm-1,GCST90042695,depression-family-sibling,-0.0068,0.1035,-0.0661,9.473000e-01,0.0127,0.0015,1.0179,0.0079,-0.0055,0.0052
2015,GCST90042698,lung-cancer-family-sibling,GCST90137411,bcc-2,0.1294,0.0816,1.5860,1.127000e-01,0.0701,0.0119,0.9732,0.0229,0.0043,0.0053

In [ ]:
### Add bonferroni correction

In [4]:
# Perform Benjamini-Yekutieli correction
ldsc_csv['adjusted_p_by'] = stats.false_discovery_control(ldsc_csv["p"].values, method='by')
ldsc_csv['adjusted_p_bh'] = stats.false_discovery_control(ldsc_csv["p"].values, method='bh')

# adjusted_p_values_by
ldsc_csv.head()

,id_1,label_1,id_2,label_2,rg,se,z,p,h2_obs,h2_obs_se,h2_int,h2_int_se,gcov_int,gcov_int_se,adjusted_p_by,adjusted_p_bh
0,GCST90042682,depression-family-mother,GCST90011808,prostate-cancer-3,-0.0540,0.0842,-0.6406,0.5218,0.0332,0.0046,1.0536,0.0197,0.0092,0.0054,1.000000,0.691162
1,GCST90011816,cervical-cancer-2,GCST90042670,prostate-cancer-father,-0.0502,0.1571,-0.3197,0.7492,0.0066,0.0013,1.0194,0.0085,0.0002,0.0051,1.000000,0.849074
2,GCST004748,lung-carcinoma-1,GCST90042696,prostate-cancer-sibling,0.0305,0.1860,0.1640,0.8697,0.0013,0.0011,1.0049,0.0063,-0.0020,0.0052,1.000000,0.924576
3,GCST003769,depression-symptoms,GCST90043894,prostate-cancer-1,-0.0065,0.0700,-0.0922,0.9265,0.0255,0.0037,1.0467,0.0156,0.0050,0.0052,1.000000,0.961876
4,GCST90255675,crc-cancer-1,GCST90275154,mdd-sex-M1,0.0844,0.0382,2.2088,0.0272,0.1190,0.0093,1.0270,0.0076,-0.0034,0.0060,0.619171,0.075635

In [5]:
#Save the DataFrame with adjusted values back to a new CSV file
ldsc_csv.to_csv("/home/maria/git/SOROLLA/Results/ldsc_genetic_correlation_corrected.csv", index=False)